@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to generate irrigation program with start on desired date
    activate System

        System --> Agent : generate the plan and CSV file with plan details
    deactivate System



@enduml